name: Linux build
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v4
            
            - name: Install tools
              run: |
                sudo apt-get update
                sudo apt-get install -y cmake
                
            - name: Build
              run: |
                cmake -H. -B build -DCMAKE_INSTALL_PREFIX=_install
                cmake --build build
